name: Deploy static app

inputs:
  app-name:
    type: string
    required: true
  access-key:
    type: string
    required: true
  secret-key:
    type: string
    required: true
  project-id:
    type: string
    required: true
  organization-id:
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Set variables
      id: vars
      run: |
        echo "branch-name=$(echo $GITHUB_REF_NAME  | sed 's/\//_/g')" >> $GITHUB_OUTPUT

    - name: Initialize Scaleway CLI
      uses: scaleway/action-scw@v0
      with:
        save-config: true
        access-key: ${{ inputs.access-key }}
        secret-key: ${{ inputs.secret-key }}
        default-project-id: ${{ inputs.project-id }}
        default-organization-id: ${{ inputs.organization-id }}

    - name: Download artifacts
      uses: actions/download-artifact@v5
      with:
        name: build-artifacts-${{ github.run_number }}
        path: apps

    - name: Prepare environment
      run: |
        [ -f "apps/${{ inputs.app-name }}/scripts/prepare-env" ] \
          && ./apps/${{ inputs.app-name }}/scripts/prepare-env
      shell: bash
      env:
        BUILD_ENV: production
        REPRO_APP_URL: https://app.reproqa.dev/branch/${{ steps.vars.outputs.branch-name }}
        # TODO: Provide branch build of API server
        REPRO_API_URL: https://api.reproqa.dev

    - name: Upload build artifacts
      run: |
        echo "Upload build artifacts with SCW API"
        ls -R apps/${{ inputs.app-name }}/dist
      shell: bash
