FROM node:22-slim AS base
WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable
RUN corepack prepare pnpm@8.3.1 --activate

RUN pnpm add --global @moonrepo/cli

COPY ./patches/ ./patches/

# Install PNPM packages only if dependency versions have changed
COPY pnpm-lock.yaml ./
RUN pnpm fetch

# Add source files and install dependencies from store
COPY . .
RUN pnpm install --offline
