apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
  labels:
    app: db-migrations
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: db-migrations
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrations
          image: api-server-migrations
          imagePullPolicy: Never
          command: ["moon", "run", "repro/api-server:migrate"]
          env:
          {{- range $key, $val := .Values.vars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
