import { fontSize, lineHeight, spacing } from '@repro/design'

export const TOOL_RESULT_ROW_STYLES = {
  gap: spacing.lg,
  consoleHeaderGap: spacing.sm,
  lineGap: spacing.xs,
  paddingBlockConsole: spacing.md,
  paddingBlockNetwork: spacing.lg,
  paddingInline: spacing.xl,
  borderWidth: 1,
  timeColumnMinWidth: 72,
  rowContentShift: 72 + spacing.lg,
  consoleContentShift: 72 + spacing.xl,
  timeActionConsoleTop: -3,
  timeActionConsoleLeft: -10,
  rowFontSize: fontSize.xs,
  rowLineHeight: lineHeight.normal,
  actionGap: spacing.xs,
  actionPadding: spacing.sm,
  actionIconSize: 13,
  actionLabelFontSize: fontSize.xs,
  actionOpacityHidden: 0,
  actionOpacityVisible: 1,
  actionLabelSpacing: spacing.sm,
} as const
