PROJECT_ROOT = os.path.join(os.getcwd(), '../../..')

local_resource(
    'admin',
    serve_cmd='portless admin.repro moon run repro/admin:dev',
    serve_dir=PROJECT_ROOT,
    serve_env={
        'BUILD_ENV': 'development',
        'REPRO_WORKSPACE_URL': 'http://app.repro.localhost:1355',
        'REPRO_ADMIN_URL': 'http://admin.repro.localhost:1355',
        'REPRO_API_URL': 'http://api.repro.localhost:1355',
    },
    deps=[
        os.path.join(PROJECT_ROOT, 'apps/admin/src'),
        os.path.join(PROJECT_ROOT, 'apps/admin/package.json'),
    ],
    resource_deps=['dependencies', 'portless-proxy'],
    allow_parallel=True,
    links=['http://admin.repro.localhost:1355'],
    labels=['app'],
)
