#!/usr/bin/env bash

set -euo pipefail

cmd="build"

while getopts "s" param; do
  case "$param" in
    s) cmd="serve";;
  esac
done

if [ "$cmd" = "serve" ]; then
  pnpm exec vite
else
  pnpm exec vite build
fi
