#!/usr/bin/env bash

set -euo pipefail

project_dir=$(realpath "$(dirname $0)/..")
build_dir="$project_dir/dist"

for input in "$build_dir"/*.template.html; do
  if [ -f "$input" ]; then
    output="${input%.template.html}.html"
    vars=$(grep -oE '\$[a-zA-Z0-9_]+' "$input" | sort -u | tr '\n' ',')
    envsubst "$vars" < "$input" > "$output"
  fi
done
