PROJECT_ROOT = os.path.join(os.getcwd(), '../../..')

local_resource(
    'workspace',
    serve_cmd='portless app.repro moon run repro/workspace:dev',
    serve_dir=PROJECT_ROOT,
    serve_env={
        'BUILD_ENV': 'development',
        'REPRO_APP_URL': 'http://app.repro.localhost:1355',
        'REPRO_API_URL': 'http://api.repro.localhost:1355',
    },
    deps=[
        os.path.join(PROJECT_ROOT, 'apps/workspace/src'),
        os.path.join(PROJECT_ROOT, 'apps/workspace/package.json'),
    ],
    resource_deps=['dependencies', 'portless-proxy'],
    allow_parallel=True,
    links=['http://app.repro.localhost:1355'],
    labels=['app'],
)
