load('ext://helm_resource', 'helm_resource', 'helm_repo')

helm_repo(
    'bitnami',
    'https://charts.bitnami.com/bitnami',
    labels=['infra']
)

helm_resource(
    name='database',
    chart='bitnami/postgresql',
    namespace='default',
    resource_deps=['bitnami'],
    flags=[
        '--set=image.repository=bitnamilegacy/postgresql',
        '--set=global.postgresql.auth.username=repro',
        '--set=global.postgresql.auth.password=repro',
        '--set=global.postgresql.auth.database=repro'
    ],
    port_forwards='5432',
    labels=['infra']
)

helm_repo(
    'seaweedfs',
    'https://seaweedfs.github.io/seaweedfs/helm',
    labels=['infra']
)

k8s_yaml('./s3-config-secret.yaml')

local_resource(
    'storage-bucket-hook-cleanup',
    cmd='kubectl delete job storage-bucket-hook --ignore-not-found',
    labels=['infra']
)

helm_resource(
    name='storage',
    chart='seaweedfs/seaweedfs',
    namespace='default',
    resource_deps=['seaweedfs', 'storage-bucket-hook-cleanup'],
    flags=['--values=./storage-values.yaml'],
    labels=['infra']
)
