load('ext://helm_resource', 'helm_resource', 'helm_repo')

helm_repo(
    'bitnami',
    'https://charts.bitnami.com/bitnami',
    labels=['infra']
)

helm_resource(
    name='database',
    chart='bitnami/postgresql',
    namespace='default',
    resource_deps=['bitnami'],
    flags=[
        '--set=image.repository=bitnamilegacy/postgresql',
        '--set=image.tag=17',
        '--set=global.postgresql.auth.username=repro',
        '--set=global.postgresql.auth.password=repro',
        '--set=global.postgresql.auth.database=repro'
    ],
    port_forwards='15432:5432',
    labels=['infra']
)

helm_repo(
    'seaweedfs',
    'https://seaweedfs.github.io/seaweedfs/helm',
    labels=['infra']
)

_s3_secret_yaml = read_file('./s3-config-secret.yaml')

local_resource(
    'storage-s3-config',
    cmd=['sh', '-c', 'echo "$S3_SECRET_YAML" | kubectl apply -f -'],
    env={'S3_SECRET_YAML': str(_s3_secret_yaml)},
    labels=['infra'],
    deps=['./s3-config-secret.yaml']
)

local_resource(
    'storage-bucket-hook-cleanup',
    cmd='kubectl delete job storage-bucket-hook --ignore-not-found',
    labels=['infra']
)

helm_resource(
    name='storage',
    chart='seaweedfs/seaweedfs',
    namespace='default',
    resource_deps=['seaweedfs', 'storage-bucket-hook-cleanup', 'storage-s3-config'],
    flags=['--values=./storage-values.yaml'],
    labels=['infra']
)

local_resource(
    'database-ready',
    cmd='kubectl wait --namespace default --for=condition=ready pod -l app.kubernetes.io/instance=database,app.kubernetes.io/name=postgresql --timeout=120s',
    resource_deps=['database'],
    labels=['infra']
)

local_resource(
    'storage-ready',
    cmd='kubectl wait --namespace default --for=jsonpath="{.subsets[*].addresses[*].ip}" endpoints/storage-seaweedfs-s3 --timeout=120s',
    resource_deps=['storage'],
    labels=['infra']
)
