local_resource(
  'capture',
  serve_cmd='moon run repro/capture:watch',
  serve_env={
    'BUILD_ENV': 'development',
    'REPRO_APP_URL': 'http://app.repro.localhost:1355',
    'REPRO_API_URL': 'http://api.repro.localhost:1355'
  },
  resource_deps=['dependencies', 'workspace'],
  allow_parallel=True,
  labels=['extension']
)
